###Register check if not working
POST localhost:3000/user/add
Content-Type: application/json

{
  "firstname": "asdf",
  "lastname": "qwertz",
  "email": "asdf@asf.ch",
  "password": "1234"
}

###Register Test User
POST localhost:3000/user/add
Content-Type: application/json

{
  "firstname": "a",
  "lastname": "k",
  "email": "a.k@gmail.co",
  "password": "123",
  "password2": "123"
}

###Login
POST localhost:3000/user/verify
Content-Type: application/json

{
  "email": "a.k@gmail.co",
  "password": "123"
}

###add_books
POST  localhost:3000/admin
Content-Type: application/json

{
  "title":"adf",
  "author": "adfs",
  "publisher": "af",
  "isbn": "sadf",
  "keywords": "fa",
  "type": "Buch",
  "year": "1970",
  "blurb": "afd",
  "small_desc": "af ",
  "img": "",
  "img_desc": "",
  "read": ""
}