# fly.toml app configuration file generated for bibliothek on 2023-06-15T11:06:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bibliothek"
primary_region = "arn"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"
